### ISSUE TITLE
Assertion Error - Passing features to Sklearn

### ISSUE THREAD

**Issue by HeinRique** [nabeel-oz/qlik-py-tools#31]
Hi Nabeel, 

Hope you doing well.
I was trying to run the train and test model, fitting my data model. But something is occurring very often.
Every time that I try to load my data, the same error keeps showing up:
 
![image](https://user-images.githubusercontent.com/19478251/59060054-97742300-8876-11e9-8729-c992c0c3a661.png)

The number of columns seems to never match the data that I'm loading. It's not even the real columns quantity (17 columns)

Here is a sample of my data. I already checked the fields and special symbols, without any success.

Name | Variable_Type | Data_Type | Feature_Strategy | Hash_Features
-- | -- | -- | -- | --
IDPROCESSO | identifier | int | scaling |  
HIDROLISEVOLADITIVO | feature | float | scaling |  
HIDROLISEDURPROCESSO | feature | float | scaling |  
HIDROLISED075315GSD | feature | int | scaling |  
HIDROLISED075315EFICIENCIA | target | str | one hot encoding
FERVURA01VOLINID0753 | feature | float | scaling |  
FERVURA01TMPFIMTIC0753PV | feature | float | scaling |  
FERVURA01DURFERVURA01 | feature | float | scaling |  
FERVURA01ABEFIMTIC0753OUT | feature | float | scaling |  
DESCARGATMPINITIC0753PV | feature | float | scaling |  
DESCARGATMPFIMTIC0753PV | feature | float | scaling |  
DESCARGADURDESCD0753 | feature | float | scaling |  
DESCARGADURABERTURAHS07571 | feature | float | scaling |  
DESCARGAABEINITIC0753OUT | feature | float | scaling |  
DESCARGAABEFIMTIC0753OUT | feature | float | scaling |  
AQUECIMENTOVOLFIMD0753 | feature | float | scaling |  
AQUECIMENTODURAQUECHS07533 | feature | float | scaling |  

------###-------

N_Features
--
3\|148.94\|0.17\|0\|95.6\|74.09\|110.11\|0.03\|34.47\|106.83\|80.24\|0.01\|0.01\|0\|0\|74.09\|0.04
7\|135.4\|0.45\|0\|96.3\|74.39\|109.88\|0.03\|40.66\|104.91\|77.01\|0.26\|0.26\|0\|0\|74.39\|0.05
8\|144\|0.18\|0\|96.5\|74.89\|109.73\|0.03\|41.23\|106.66\|81.01\|0.01\|0.01\|0\|0\|74.89\|0.05
10\|136.54\|0.19\|0\|96.7\|74.55\|109.79\|0.03\|41.13\|105.99\|80.39\|0.01\|0.01\|0\|0\|74.55\|0.05
11\|78.39\|0.31\|0\|96\|91.98\|110.11\|0.03\|34.03\|102.87\|74.77\|0.04\|0.04\|0\|0\|91.98\|0.06
13\|95.3\|0.22\|0\|95.8\|93.06\|109.67\|0.03\|43.53\|105.73\|74.61\|0.02\|0.02\|0\|0\|93.06\|0.07
14\|133.56\|0.24\|0\|96\|92.61\|109.97\|0.03\|41.35\|103.05\|73.14\|0.03\|0.03\|0\|0\|92.61\|0.05
15\|142.05\|0.41\|0\|95.9\|92.39\|109.26\|0.03\|50.26\|94.51\|70.63\|0.02\|0.02\|1.46\|1.46\|92.39\|0.07
16\|140.91\|0.31\|0\|96\|92.25\|109.31\|0.03\|50.45\|107.33\|82.76\|0.02\|0.02\|15\|15\|92.25\|0.07
21\|131.99\|0.22\|0\|96.6\|90.68\|109.78\|0.03\|46.31\|104.92\|75.26\|0.01\|0.01\|0\|0\|90.68\|0.06
22\|129.75\|0.2\|0\|95.6\|90.94\|109.6\|0.03\|44.03\|106.38\|75.93\|0.01\|0.01\|0\|0\|90.94\|0.06
28\|140.12\|0.19\|0\|95.8\|89.09\|109.65\|0.03\|44.03\|106.23\|74.92\|0.01\|0.01\|0\|0\|89.09\|0.05
34\|141.7\|0.25\|0\|95.6\|0\|0\|0\|0\|106.46\|76.38\|0.01\|0.01\|0\|0\|0\|0
40\|129.2\|0.2\|0\|95.9\|88.99\|109.83\|0.03\|40.04\|107.37\|74.45\|0.01\|0.01\|0\|0\|88.99\|0.05
45\|121.79\|0.21\|0\|96.3\|89.46\|110.06\|0.03\|38.13\|106.92\|72.48\|0.02\|0.02\|0\|0\|89.46\|0.05
61\|129.67\|0.24\|0\|96.1\|90.3\|110.12\|0.03\|31.75\|105.27\|75.29\|0.02\|0.02\|0\|0\|90.3\|0.05
64\|125.19\|0.18\|0\|95.7\|89.27\|110.2\|0.03\|31.96\|107.12\|74.81\|0.02\|0.02\|0\|0\|89.27\|0.05
66\|138.72\|0.21\|0\|95.8\|89.79\|110.17\|0.03\|31.46\|106.68\|73.84\|0.02\|0.02\|0\|0\|89.79\|0.05

I've tried to use only integer numbers: Not working. I've noticed that it returns an error if I tag the target field as a float.

If possible, I would like to understand how the strings are broken on python to run the algorithms.

Thank you for your help.

Cosme Henrique.

**Comment by nabeel-oz** [comment]
Hi @HeinRique ,

Thanks for the detailed description. 

From the error stack I can see that the problem occurs after we have fit the model and are trying to get the evaluation metrics. The code is trying to get classification metrics, but it looks like your target is a number rather than the discrete classes required for classification. So I suspect the problem is that you are using a classification estimator when you should be using a regression estimator.

I also see that your target field is set as a string in the feature definitions but is actually a float. Using one hot encoding on this field will split it into multiple columns; one for each unique value, which is probably a mistake. Just leave the target as an int or float with the feature strategy as none, and frame your model as a regression problem. If you want to do classification you would convert this continuous variable into a discrete one, for example by bucketing the numeric values into fixed classes in Qlik.

The n_features input you are sending looks ok. The SSE breaks the input into multiple columns on the `|` delimiter and then converts data types based on the feature definitions you send to the model. The feature strategies such as scaling and one hot encoding are then applied which may result in a different number of columns than the input. You can see the transformations the data goes through by passing `debug=true` in the `ExecutionArgs`.

**Comment by HeinRique** [comment]
Hi @nabeel-oz !

Thank you for the quick answer. I've made some changes and I could pass through that error.
Now I'm with a little problem on the "Feature Importances" section that shows me that: 

> "Importances do not sum to a positive value"

But I'll make some research to figure it out. If you have some tip, I'll be grateful. 

Thank you, once again, for your help.

**Comment by nabeel-oz** [comment]
Hi @HeinRique ,

This new error would be coming from the Skater package. There's an additional description along with the error that should give the possible reasons:
1. 0 or infinite divisions
2. perturbed values == original values
3. feature is a constant 

The importances are calculated by changing the value of features and checking how the model behaves compared to the original values. Could there be a reason this is not possible for a particular feature in your dataset? You can turn on debugging and look at the input dataframe before we fit the model. The most obvious issue would be a constant value across all samples.

If you don't really need the feature importances, you could turn them off by passing `calculate_importances=false` argument in the `ExecutionArgs`.

**Comment by HeinRique** [comment]
Hi @nabeel-oz !

Once again, thank you for your help. I got it.

With this information, I could complete my train model.

Congratulations for this excellent tool!
Regards!

**Comment by HeinRique** [comment]
Hey @nabeel-oz ,
Sorry to reopen this error, but turns out that the prediction part brought us another weird error.

I'm using the same data mentioned above and adapting your qvf sample for prediction.
The script loads fine. But when I use the expression on a chart, it actually stops the Qlik Desktop and raises this error on console.
Here is the console:
![Screenshot_7](https://user-images.githubusercontent.com/19478251/59299288-a8e87100-8c62-11e9-9a94-4c9971faf1b8.png)

Here is what happens with Qlik (I needed to restart the app after this) :
![Screenshot_6](https://user-images.githubusercontent.com/19478251/59299352-d2a19800-8c62-11e9-9c17-03e437abe42e.png)

After restart de QS Desktop, it gets the Capabilities all over again.
The expression:
![Screenshot_8](https://user-images.githubusercontent.com/19478251/59299929-43957f80-8c64-11e9-8c7d-a8a0857dbc84.png)

I thought that, after training data, the prediction part would be easier since the model is stored as a .joblib.

I apologize for being annoying, but I'm out of options here.

**Comment by nabeel-oz** [comment]
@HeinRique , no need to apologize, this is what the issues section is for!

It looks like there is a bug in the code when returning a numerical prediction. The quick fix is to update the following code block in the _utils.py file from rows 73 to 74. You'll need to update the file under `qlik-py-tools\qlik-py-env\core`.

```
            # Convert values to type SSE.Dual according to the template list
            if template[0] == "str":
                this_row.append(SSE.Dual(strData=row))
```

Replace with:

```
            # Convert values to type SSE.Dual according to the template list
            if template[0] == "str":
                if type(row) is not str:
                        row = "{0:.5f}".format(row)
                this_row.append(SSE.Dual(strData=row))
```

I'll try to get a proper fix and release in soon.

**Comment by nabeel-oz** [comment]
Hi @HeinRique , I've published a fix but would like your help to test it on your data. Can you grab the following files from the link below:
- \_\_main\_\_.py
- _sklearn.py
- _utils.py

https://github.com/nabeel-oz/qlik-py-tools/tree/master/core

Paste these to your `qlik-py-tools\qlik-py-env\core` directory, overwriting the existing files.

Then restart the SSE and try getting predictions from the existing model.

**Comment by HeinRique** [comment]
Hi @nabeel-oz 

I've made the changes that you mentioned. The error is gone, but it's not showing any predictions.

![Screenshot_9](https://user-images.githubusercontent.com/19478251/59359545-ea315d00-8d04-11e9-9244-e3021ded094e.png)

I've run the Train & Test once again, to make sure that the score still the same and nothing has changed.

I downloaded the whole repository e replace all files from py-tools, but predictions still not coming.

 I'm sending you a sample of my data so it can help in any way. Also sending you de .joblib from the model that I'm using.

[Regression Sample.zip](https://github.com/nabeel-oz/qlik-py-tools/files/3281832/Regression.Sample.zip)

If you need any other file or evidence, let me know.

Thank you for your suport!

**Comment by nabeel-oz** [comment]
@HeinRique , I don't see the prediction function (functionID 14) being executed based on the logs. So I suspect this (hopefully) final hurdle is an incorrect prediction expression. Can you send me your predictions app as well so I can check?

**Comment by nabeel-oz** [comment]
After some testing I realised that I missed a limitation of SSE functions; they can only have one return type. So the changes I made yesterday to return a numeric or string prediction depending on the target doesn't quite work for chart expressions. It does work when getting predictions in the load script.

I've just gone back to the simpler approach of returning the prediction as a string in all cases and letting Qlik convert it to a dual automatically. Can you grab the latest `__main.py__` and `_sklearn.py` files and replace them in your `qlik-py-tools\qlik-py-env\core` directory once more? You don't need to get the whole repository again.

https://github.com/nabeel-oz/qlik-py-tools/tree/master/core

Here's an app with your data that I used for testing: 
[_Git Issue 31.zip](https://github.com/nabeel-oz/qlik-py-tools/files/3283934/_Git.Issue.31.zip)

**Comment by HeinRique** [comment]
Hi @nabeel-oz ,

Good news: it works!  First of all, thank you for your support.

Besides this, I've noticed that in your app "_Git issue 31", the "Predict Dimension" and "Predict Measure" wasn't working. After some changes, I realize that only "Predict Dimension" wasn't working. If you remove it from the table chart, you'll see that the measure one starts to work.

On my app test, both of them works just fine. So I tried to:
- **Copy my measure to your app chart**: it was the same syntax. it didn't work.
- **Copy my chart to your app**: the dimension one stop working.
- **Check the load script**: the "Feature Expression" tab was identical. 
- **Load my data in your app**: after this, all the features worked. Dimension, Measure and Load Script.

I don't know why it happened. I think that could be the size of data(?). Is it a real problem or not?
The SSE doesn't show any error, by the way.

So, for me, the py-tool is working and I really thank you for your help.

If there is anything you need to evaluate this weird behavior mentioned above, just let me know.

Now I'll join this solution with my ETL model and see the magic!

Thank you, once again.

**Comment by nabeel-oz** [comment]
Hi @HeinRique ,

That's great news! Glad you got your model working.

The behavior you described is indeed quite odd. I can't think of a reason why the measure expression would work, but the dimension wouldn't, or why a reload would fix everything. I did build that app in the June preview version of Qlik Sense Desktop, so that may be a factor.
